general.import = [
     "~/.config/alacritty/themes/themes/xterm.toml"
]
general.live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
opacity = 0.6
dynamic_padding = true
title="terminal"
decorations="None"
padding = {x = 6, y = 6}

[terminal.shell]
program = "tmux"

[font]
offset.y = 2
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]

family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]

family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
