font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Heavy
italic_font      FiraCode Nerd Italic
bold_italic_font FiraCode Nerd Heavy Italic

font_size 16.0
force_ltr no

cursor_shape block

url_color #89b4fa
url_style curly

open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes

hide_window_decorations no
window_padding_width 5

foreground #cdd6f4
background #1e1e2e
background_opacity 0.97

color0 #1e1e2e
color8 #7f849c

color1 #f38ba8
color9 #eba0ac

color2  #a6e3a1
color10 #94e2d5

color3  #f9e2af
color11 #fab387

color4  #89b4fa
color12 #74c7ec

color5  #cba6f7
color13 #f5c2e7

color6  #89dceb
color14 #94e2d5

color7  #bac2de
color15 #cdd6f4

mark1_foreground black
mark1_background #94e2d5

mark2_foreground black
mark2_background #f2cdcd

mark3_foreground black
mark3_background #cba6f7

shell tmux
editor nvim
